<?php
/**
 * GetManifestResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  YagaSchedule\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yaga order gateway
 *
 * Common schema for Yaga schedule requests. Swagger
 *
 * OpenAPI spec version: 18.40.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Services\YagaAPI15\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the GetManifestResult model.
 *
 * @package YagaSchedule\Server\Model
 * @author  Swagger Codegen team
 */
class GetManifestResult
{
        /**
     * @var YagaSchedule\Server\Model\Manifest|null
     * @SerializedName("manifest")
     * @Assert\Type("YagaSchedule\Server\Model\Manifest")
     * @Type("YagaSchedule\Server\Model\Manifest")
     */
    protected $manifest;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->manifest = isset($data['manifest']) ? $data['manifest'] : null;
    }

    /**
     * Gets manifest.
     *
     * @return \App\Services\YagaAPI15\Model\Manifest|null
     */
    public function getManifest()
    {
        return $this->manifest;
    }

    /**
     * Sets manifest.
     *
     * @param YagaSchedule\Server\Model\Manifest|null $manifest
     *
     * @return $this
     */
    public function setManifest(Manifest $manifest = null)
    {
        $this->manifest = $manifest;

        return $this;
    }
}


