<?php
/**
 * GetVenuesResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  YagaSchedule\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yaga order gateway
 *
 * Common schema for Yaga schedule requests. Swagger
 *
 * OpenAPI spec version: 18.40.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Services\YagaAPI15\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the GetVenuesResult model.
 *
 * @package YagaSchedule\Server\Model
 * @author  Swagger Codegen team
 */
class GetVenuesResult
{
        /**
     * @var YagaSchedule\Server\Model\Venue[]|null
     * @SerializedName("venues")
     * @Assert\All({
     *   @Assert\Type("YagaSchedule\Server\Model\Venue")
     * })
     * @Type("array<YagaSchedule\Server\Model\Venue>")
     */
    protected $venues;

    /**
     * @var YagaSchedule\Server\Model\ListInfo|null
     * @SerializedName("paging")
     * @Assert\Type("YagaSchedule\Server\Model\ListInfo")
     * @Type("YagaSchedule\Server\Model\ListInfo")
     */
    protected $paging;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->venues = isset($data['venues']) ? $data['venues'] : null;
        $this->paging = isset($data['paging']) ? $data['paging'] : null;
    }

    /**
     * Gets venues.
     *
     * @return \App\Services\YagaAPI15\Model\Venue[]|null
     */
    public function getVenues()
    {
        return $this->venues;
    }

    /**
     * Sets venues.
     *
     * @param YagaSchedule\Server\Model\Venue[]|null $venues
     *
     * @return $this
     */
    public function setVenues(Venue $venues = null)
    {
        $this->venues = $venues;

        return $this;
    }

    /**
     * Gets paging.
     *
     * @return \App\Services\YagaAPI15\Model\ListInfo|null
     */
    public function getPaging()
    {
        return $this->paging;
    }

    /**
     * Sets paging.
     *
     * @param YagaSchedule\Server\Model\ListInfo|null $paging
     *
     * @return $this
     */
    public function setPaging(ListInfo $paging = null)
    {
        $this->paging = $paging;

        return $this;
    }
}


