<?php
/**
 * ListInfo
 *
 * PHP version 5
 *
 * @category Class
 * @package  YagaSchedule\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yaga order gateway
 *
 * Common schema for Yaga schedule requests. Swagger
 *
 * OpenAPI spec version: 18.40.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Services\YagaAPI15\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ListInfo model.
 *
 * Информация о текущей странице в выдаче некоторых методов.  limit  (*) - мексимальное число элементов на странице offset (*) - смещение total  (*) - общее число элементов
 *
 * @package YagaSchedule\Server\Model
 * @author  Swagger Codegen team
 */
class ListInfo
{
        /**
     * @var string|null
     * @SerializedName("limit")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $limit;

    /**
     * @var string|null
     * @SerializedName("offset")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $offset;

    /**
     * @var string|null
     * @SerializedName("total")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $total;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->limit = isset($data['limit']) ? $data['limit'] : null;
        $this->offset = isset($data['offset']) ? $data['offset'] : null;
        $this->total = isset($data['total']) ? $data['total'] : null;
    }

    /**
     * Gets limit.
     *
     * @return string|null
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Sets limit.
     *
     * @param string|null $limit
     *
     * @return $this
     */
    public function setLimit($limit = null)
    {
        $this->limit = $limit;

        return $this;
    }

    /**
     * Gets offset.
     *
     * @return string|null
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Sets offset.
     *
     * @param string|null $offset
     *
     * @return $this
     */
    public function setOffset($offset = null)
    {
        $this->offset = $offset;

        return $this;
    }

    /**
     * Gets total.
     *
     * @return string|null
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Sets total.
     *
     * @param string|null $total
     *
     * @return $this
     */
    public function setTotal($total = null)
    {
        $this->total = $total;

        return $this;
    }
}


