<?php
/**
 * Person
 *
 * PHP version 5
 *
 * @category Class
 * @package  YagaSchedule\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yaga order gateway
 *
 * Common schema for Yaga schedule requests. Swagger
 *
 * OpenAPI spec version: 18.40.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Services\YagaAPI15\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Person model.
 *
 * @package YagaSchedule\Server\Model
 * @author  Swagger Codegen team
 */
class Person
{
        /**
     * @var string|null
     * @SerializedName("id")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $id;

    /**
     * @var string|null
     * @SerializedName("name")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $name;

    /**
     * @var YagaSchedule\Server\Model\PersonType|null
     * @SerializedName("type")
     * @Assert\Type("YagaSchedule\Server\Model\PersonType")
     * @Type("YagaSchedule\Server\Model\PersonType")
     */
    protected $type;

    /**
     * @var \DateTime|null
     * @SerializedName("initDate")
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected $initDate;

    /**
     * @var \DateTime|null
     * @SerializedName("endDate")
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected $endDate;

    /**
     * @var string|null
     * @SerializedName("briefDescription")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $briefDescription;

    /**
     * @var string|null
     * @SerializedName("fullDescription")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $fullDescription;

    /**
     * @var string[]|null
     * @SerializedName("synonyms")
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected $synonyms;

    /**
     * @var YagaSchedule\Server\Model\Tag[]|null
     * @SerializedName("tags")
     * @Assert\All({
     *   @Assert\Type("YagaSchedule\Server\Model\Tag")
     * })
     * @Type("array<YagaSchedule\Server\Model\Tag>")
     */
    protected $tags;

    /**
     * @var YagaSchedule\Server\Model\Image|null
     * @SerializedName("image")
     * @Assert\Type("YagaSchedule\Server\Model\Image")
     * @Type("YagaSchedule\Server\Model\Image")
     */
    protected $image;

    /**
     * @var YagaSchedule\Server\Model\SourceRef[]|null
     * @SerializedName("integrations")
     * @Assert\All({
     *   @Assert\Type("YagaSchedule\Server\Model\SourceRef")
     * })
     * @Type("array<YagaSchedule\Server\Model\SourceRef>")
     */
    protected $integrations;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->name = isset($data['name']) ? $data['name'] : null;
        $this->type = isset($data['type']) ? $data['type'] : null;
        $this->initDate = isset($data['initDate']) ? $data['initDate'] : null;
        $this->endDate = isset($data['endDate']) ? $data['endDate'] : null;
        $this->briefDescription = isset($data['briefDescription']) ? $data['briefDescription'] : null;
        $this->fullDescription = isset($data['fullDescription']) ? $data['fullDescription'] : null;
        $this->synonyms = isset($data['synonyms']) ? $data['synonyms'] : null;
        $this->tags = isset($data['tags']) ? $data['tags'] : null;
        $this->image = isset($data['image']) ? $data['image'] : null;
        $this->integrations = isset($data['integrations']) ? $data['integrations'] : null;
    }

    /**
     * Gets id.
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param string|null $id
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string|null $name
     *
     * @return $this
     */
    public function setName($name = null)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets type.
     *
     * @return \App\Services\YagaAPI15\Model\PersonType|null
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param YagaSchedule\Server\Model\PersonType|null $type
     *
     * @return $this
     */
    public function setType(PersonType $type = null)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets initDate.
     *
     * @return \DateTime|null
     */
    public function getInitDate()
    {
        return $this->initDate;
    }

    /**
     * Sets initDate.
     *
     * @param \DateTime|null $initDate
     *
     * @return $this
     */
    public function setInitDate(\DateTime $initDate = null)
    {
        $this->initDate = $initDate;

        return $this;
    }

    /**
     * Gets endDate.
     *
     * @return \DateTime|null
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * Sets endDate.
     *
     * @param \DateTime|null $endDate
     *
     * @return $this
     */
    public function setEndDate(\DateTime $endDate = null)
    {
        $this->endDate = $endDate;

        return $this;
    }

    /**
     * Gets briefDescription.
     *
     * @return string|null
     */
    public function getBriefDescription()
    {
        return $this->briefDescription;
    }

    /**
     * Sets briefDescription.
     *
     * @param string|null $briefDescription
     *
     * @return $this
     */
    public function setBriefDescription($briefDescription = null)
    {
        $this->briefDescription = $briefDescription;

        return $this;
    }

    /**
     * Gets fullDescription.
     *
     * @return string|null
     */
    public function getFullDescription()
    {
        return $this->fullDescription;
    }

    /**
     * Sets fullDescription.
     *
     * @param string|null $fullDescription
     *
     * @return $this
     */
    public function setFullDescription($fullDescription = null)
    {
        $this->fullDescription = $fullDescription;

        return $this;
    }

    /**
     * Gets synonyms.
     *
     * @return string[]|null
     */
    public function getSynonyms()
    {
        return $this->synonyms;
    }

    /**
     * Sets synonyms.
     *
     * @param string[]|null $synonyms
     *
     * @return $this
     */
    public function setSynonyms($synonyms = null)
    {
        $this->synonyms = $synonyms;

        return $this;
    }

    /**
     * Gets tags.
     *
     * @return \App\Services\YagaAPI15\Model\Tag[]|null
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Sets tags.
     *
     * @param YagaSchedule\Server\Model\Tag[]|null $tags
     *
     * @return $this
     */
    public function setTags(Tag $tags = null)
    {
        $this->tags = $tags;

        return $this;
    }

    /**
     * Gets image.
     *
     * @return \App\Services\YagaAPI15\Model\Image|null
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Sets image.
     *
     * @param YagaSchedule\Server\Model\Image|null $image
     *
     * @return $this
     */
    public function setImage(Image $image = null)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Gets integrations.
     *
     * @return \App\Services\YagaAPI15\Model\SourceRef[]|null
     */
    public function getIntegrations()
    {
        return $this->integrations;
    }

    /**
     * Sets integrations.
     *
     * @param YagaSchedule\Server\Model\SourceRef[]|null $integrations
     *
     * @return $this
     */
    public function setIntegrations(SourceRef $integrations = null)
    {
        $this->integrations = $integrations;

        return $this;
    }
}


