<?php
/**
 * SourceRef
 *
 * PHP version 5
 *
 * @category Class
 * @package  YagaSchedule\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yaga order gateway
 *
 * Common schema for Yaga schedule requests. Swagger
 *
 * OpenAPI spec version: 18.40.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Services\YagaAPI15\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the SourceRef model.
 *
 * Структура для передачи ссылок на идентификатор объекта в сторонних базах данных
 *
 * @package YagaSchedule\Server\Model
 * @author  Swagger Codegen team
 */
class SourceRef
{
        /**
     * @var string|null
     * @SerializedName("serviceId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $serviceId;

    /**
     * @var string|null
     * @SerializedName("sourceId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $sourceId;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->serviceId = isset($data['serviceId']) ? $data['serviceId'] : null;
        $this->sourceId = isset($data['sourceId']) ? $data['sourceId'] : null;
    }

    /**
     * Gets serviceId.
     *
     * @return string|null
     */
    public function getServiceId()
    {
        return $this->serviceId;
    }

    /**
     * Sets serviceId.
     *
     * @param string|null $serviceId
     *
     * @return $this
     */
    public function setServiceId($serviceId = null)
    {
        $this->serviceId = $serviceId;

        return $this;
    }

    /**
     * Gets sourceId.
     *
     * @return string|null
     */
    public function getSourceId()
    {
        return $this->sourceId;
    }

    /**
     * Sets sourceId.
     *
     * @param string|null $sourceId
     *
     * @return $this
     */
    public function setSourceId($sourceId = null)
    {
        $this->sourceId = $sourceId;

        return $this;
    }
}


