<?php
/**
 * Coordinates
 *
 * PHP version 5
 *
 * @category Class
 * @package  YagaSchedule\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yaga order gateway
 *
 * Common schema for Yaga schedule requests. Swagger
 *
 * OpenAPI spec version: 18.40.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Services\YagaAPI\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Coordinates model.
 *
 * Географические координаты  latitude  (*) - широта longitude (*) - долгота
 *
 * @package YagaSchedule\Server\Model
 * @author  Swagger Codegen team
 */
class Coordinates
{
        /**
     * @var double|null
     * @SerializedName("latitude")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected $latitude;

    /**
     * @var double|null
     * @SerializedName("longitude")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected $longitude;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->latitude = isset($data['latitude']) ? $data['latitude'] : null;
        $this->longitude = isset($data['longitude']) ? $data['longitude'] : null;
    }

    /**
     * Gets latitude.
     *
     * @return double|null
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Sets latitude.
     *
     * @param double|null $latitude
     *
     * @return $this
     */
    public function setLatitude($latitude = null)
    {
        $this->latitude = $latitude;

        return $this;
    }

    /**
     * Gets longitude.
     *
     * @return double|null
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Sets longitude.
     *
     * @param double|null $longitude
     *
     * @return $this
     */
    public function setLongitude($longitude = null)
    {
        $this->longitude = $longitude;

        return $this;
    }
}


