<?php
/**
 * GetHallsResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  YagaSchedule\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yaga order gateway
 *
 * Common schema for Yaga schedule requests. Swagger
 *
 * OpenAPI spec version: 18.40.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Services\YagaAPI\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the GetHallsResult model.
 *
 * @package YagaSchedule\Server\Model
 * @author  Swagger Codegen team
 */
class GetHallsResult
{
        /**
     * @var YagaSchedule\Server\Model\Hall[]|null
     * @SerializedName("halls")
     * @Assert\All({
     *   @Assert\Type("YagaSchedule\Server\Model\Hall")
     * })
     * @Type("array<YagaSchedule\Server\Model\Hall>")
     */
    protected $halls;

    /**
     * @var YagaSchedule\Server\Model\ListInfo|null
     * @SerializedName("paging")
     * @Assert\Type("YagaSchedule\Server\Model\ListInfo")
     * @Type("YagaSchedule\Server\Model\ListInfo")
     */
    protected $paging;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->halls = isset($data['halls']) ? $data['halls'] : null;
        $this->paging = isset($data['paging']) ? $data['paging'] : null;
    }

    /**
     * Gets halls.
     *
     * @return \App\Services\YagaAPI\Model\Hall[]|null
     */
    public function getHalls()
    {
        return $this->halls;
    }

    /**
     * Sets halls.
     *
     * @param YagaSchedule\Server\Model\Hall[]|null $halls
     *
     * @return $this
     */
    public function setHalls(Hall $halls = null)
    {
        $this->halls = $halls;

        return $this;
    }

    /**
     * Gets paging.
     *
     * @return \App\Services\YagaAPI\Model\ListInfo|null
     */
    public function getPaging()
    {
        return $this->paging;
    }

    /**
     * Sets paging.
     *
     * @param YagaSchedule\Server\Model\ListInfo|null $paging
     *
     * @return $this
     */
    public function setPaging(ListInfo $paging = null)
    {
        $this->paging = $paging;

        return $this;
    }
}


