<?php
/**
 * GetHallplanResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  YagaSchedule\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yaga order gateway
 *
 * Common schema for Yaga schedule requests. Swagger
 *
 * OpenAPI spec version: 18.40.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Services\YagaAPI\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the GetHallplanResult model.
 *
 * @package YagaSchedule\Server\Model
 * @author  Swagger Codegen team
 */
class GetHallplanResult
{
        /**
     * @var YagaSchedule\Server\Model\Hall|null
     * @SerializedName("hall")
     * @Assert\Type("YagaSchedule\Server\Model\Hall")
     * @Type("YagaSchedule\Server\Model\Hall")
     */
    protected $hall;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->hall = isset($data['hall']) ? $data['hall'] : null;
    }

    /**
     * Gets hall.
     *
     * @return \App\Services\YagaAPI\Model\Hall|null
     */
    public function getHall()
    {
        return $this->hall;
    }

    /**
     * Sets hall.
     *
     * @param YagaSchedule\Server\Model\Hall|null $hall
     *
     * @return $this
     */
    public function setHall(Hall $hall = null)
    {
        $this->hall = $hall;

        return $this;
    }
}


