<?php
/**
 * GetOrganizersResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  YagaSchedule\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yaga order gateway
 *
 * Common schema for Yaga schedule requests. Swagger
 *
 * OpenAPI spec version: 18.40.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Services\YagaAPI\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the GetOrganizersResult model.
 *
 * @package YagaSchedule\Server\Model
 * @author  Swagger Codegen team
 */
class GetOrganizersResult
{
        /**
     * @var YagaSchedule\Server\Model\Organizer[]|null
     * @SerializedName("organizers")
     * @Assert\All({
     *   @Assert\Type("YagaSchedule\Server\Model\Organizer")
     * })
     * @Type("array<YagaSchedule\Server\Model\Organizer>")
     */
    protected $organizers;

    /**
     * @var YagaSchedule\Server\Model\ListInfo|null
     * @SerializedName("paging")
     * @Assert\Type("YagaSchedule\Server\Model\ListInfo")
     * @Type("YagaSchedule\Server\Model\ListInfo")
     */
    protected $paging;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->organizers = isset($data['organizers']) ? $data['organizers'] : null;
        $this->paging = isset($data['paging']) ? $data['paging'] : null;
    }

    /**
     * Gets organizers.
     *
     * @return \App\Services\YagaAPI\Model\Organizer[]|null
     */
    public function getOrganizers()
    {
        return $this->organizers;
    }

    /**
     * Sets organizers.
     *
     * @param YagaSchedule\Server\Model\Organizer[]|null $organizers
     *
     * @return $this
     */
    public function setOrganizers(Organizer $organizers = null)
    {
        $this->organizers = $organizers;

        return $this;
    }

    /**
     * Gets paging.
     *
     * @return \App\Services\YagaAPI\Model\ListInfo|null
     */
    public function getPaging()
    {
        return $this->paging;
    }

    /**
     * Sets paging.
     *
     * @param YagaSchedule\Server\Model\ListInfo|null $paging
     *
     * @return $this
     */
    public function setPaging(ListInfo $paging = null)
    {
        $this->paging = $paging;

        return $this;
    }
}


