<?php
/**
 * Hall
 *
 * PHP version 5
 *
 * @category Class
 * @package  YagaSchedule\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yaga order gateway
 *
 * Common schema for Yaga schedule requests. Swagger
 *
 * OpenAPI spec version: 18.40.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Services\YagaAPI\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Hall model.
 *
 * Зал  id       (*) - идентификатор зала name     (*) - название организатора venue_id (*) - идентификатор площадки (Venue) levels   (*) - список уровней зала
 *
 * @package YagaSchedule\Server\Model
 * @author  Swagger Codegen team
 */
class Hall
{
        /**
     * @var string|null
     * @SerializedName("id")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $id;

    /**
     * @var string|null
     * @SerializedName("name")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $name;

    /**
     * @var string|null
     * @SerializedName("venueId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $venueId;

    /**
     * @var YagaSchedule\Server\Model\Level[]|null
     * @SerializedName("levels")
     * @Assert\All({
     *   @Assert\Type("YagaSchedule\Server\Model\Level")
     * })
     * @Type("array<YagaSchedule\Server\Model\Level>")
     */
    protected $levels;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->name = isset($data['name']) ? $data['name'] : null;
        $this->venueId = isset($data['venueId']) ? $data['venueId'] : null;
        $this->levels = isset($data['levels']) ? $data['levels'] : null;
    }

    /**
     * Gets id.
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param string|null $id
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string|null $name
     *
     * @return $this
     */
    public function setName($name = null)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets venueId.
     *
     * @return string|null
     */
    public function getVenueId()
    {
        return $this->venueId;
    }

    /**
     * Sets venueId.
     *
     * @param string|null $venueId
     *
     * @return $this
     */
    public function setVenueId($venueId = null)
    {
        $this->venueId = $venueId;

        return $this;
    }

    /**
     * Gets levels.
     *
     * @return \App\Services\YagaAPI\Model\Level[]|null
     */
    public function getLevels()
    {
        return $this->levels;
    }

    /**
     * Sets levels.
     *
     * @param YagaSchedule\Server\Model\Level[]|null $levels
     *
     * @return $this
     */
    public function setLevels(Level $levels = null)
    {
        $this->levels = $levels;

        return $this;
    }
}


