<?php
/**
 * Rating
 *
 * PHP version 5
 *
 * @category Class
 * @package  YagaSchedule\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yaga order gateway
 *
 * Common schema for Yaga schedule requests. Swagger
 *
 * OpenAPI spec version: 18.40.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Services\YagaAPI\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Rating model.
 *
 * Рейтинг события (мероприятия)  value  (*) - значение рейтинга votes  (*) - число \&quot;голосов\&quot; source (*) - источник рейтинга. Известные значения: [imdb, kinopoisk]. url    (*) - сайт рейтинга
 *
 * @package YagaSchedule\Server\Model
 * @author  Swagger Codegen team
 */
class Rating
{
        /**
     * @var double|null
     * @SerializedName("value")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected $value;

    /**
     * @var int|null
     * @SerializedName("votes")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $votes;

    /**
     * @var string|null
     * @SerializedName("source")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $source;

    /**
     * @var string|null
     * @SerializedName("url")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $url;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->value = isset($data['value']) ? $data['value'] : null;
        $this->votes = isset($data['votes']) ? $data['votes'] : null;
        $this->source = isset($data['source']) ? $data['source'] : null;
        $this->url = isset($data['url']) ? $data['url'] : null;
    }

    /**
     * Gets value.
     *
     * @return double|null
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Sets value.
     *
     * @param double|null $value
     *
     * @return $this
     */
    public function setValue($value = null)
    {
        $this->value = $value;

        return $this;
    }

    /**
     * Gets votes.
     *
     * @return int|null
     */
    public function getVotes()
    {
        return $this->votes;
    }

    /**
     * Sets votes.
     *
     * @param int|null $votes
     *
     * @return $this
     */
    public function setVotes($votes = null)
    {
        $this->votes = $votes;

        return $this;
    }

    /**
     * Gets source.
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Sets source.
     *
     * @param string|null $source
     *
     * @return $this
     */
    public function setSource($source = null)
    {
        $this->source = $source;

        return $this;
    }

    /**
     * Gets url.
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Sets url.
     *
     * @param string|null $url
     *
     * @return $this
     */
    public function setUrl($url = null)
    {
        $this->url = $url;

        return $this;
    }
}


