<?php
/**
 * SessionTime
 *
 * PHP version 5
 *
 * @category Class
 * @package  YagaSchedule\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yaga order gateway
 *
 * Common schema for Yaga schedule requests. Swagger
 *
 * OpenAPI spec version: 18.40.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Services\YagaAPI\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the SessionTime model.
 *
 * Время проведения мероприятия (сеанса)  session_start (*)   - время начала session_end         - время конца type                - тип timezone      (*)   - идентификатор таймзоны по базе https://www.iana.org/time-zones (например, Europe/Moscow)
 *
 * @package YagaSchedule\Server\Model
 * @author  Swagger Codegen team
 */
class SessionTime
{
        /**
     * @var \DateTime|null
     * @SerializedName("sessionStart")
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected $sessionStart;

    /**
     * @var \DateTime|null
     * @SerializedName("sessionEnd")
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected $sessionEnd;

    /**
     * @var YagaSchedule\Server\Model\SessionType|null
     * @SerializedName("type")
     * @Assert\Type("YagaSchedule\Server\Model\SessionType")
     * @Type("YagaSchedule\Server\Model\SessionType")
     */
    protected $type;

    /**
     * @var string|null
     * @SerializedName("timezone")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $timezone;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->sessionStart = isset($data['sessionStart']) ? $data['sessionStart'] : null;
        $this->sessionEnd = isset($data['sessionEnd']) ? $data['sessionEnd'] : null;
        $this->type = isset($data['type']) ? $data['type'] : null;
        $this->timezone = isset($data['timezone']) ? $data['timezone'] : null;
    }

    /**
     * Gets sessionStart.
     *
     * @return \DateTime|null
     */
    public function getSessionStart()
    {
        return $this->sessionStart;
    }

    /**
     * Sets sessionStart.
     *
     * @param \DateTime|null $sessionStart
     *
     * @return $this
     */
    public function setSessionStart(\DateTime $sessionStart = null)
    {
        $this->sessionStart = $sessionStart;

        return $this;
    }

    /**
     * Gets sessionEnd.
     *
     * @return \DateTime|null
     */
    public function getSessionEnd()
    {
        return $this->sessionEnd;
    }

    /**
     * Sets sessionEnd.
     *
     * @param \DateTime|null $sessionEnd
     *
     * @return $this
     */
    public function setSessionEnd(\DateTime $sessionEnd = null)
    {
        $this->sessionEnd = $sessionEnd;

        return $this;
    }

    /**
     * Gets type.
     *
     * @return \App\Services\YagaAPI\Model\SessionType|null
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param YagaSchedule\Server\Model\SessionType|null $type
     *
     * @return $this
     */
    public function setType(SessionType $type = null)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets timezone.
     *
     * @return string|null
     */
    public function getTimezone()
    {
        return $this->timezone;
    }

    /**
     * Sets timezone.
     *
     * @param string|null $timezone
     *
     * @return $this
     */
    public function setTimezone($timezone = null)
    {
        $this->timezone = $timezone;

        return $this;
    }
}


