<?php
/**
 * Session
 *
 * PHP version 5
 *
 * @category Class
 * @package  YagaSchedule\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yaga order gateway
 *
 * Common schema for Yaga schedule requests. Swagger
 *
 * OpenAPI spec version: 18.40.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Services\YagaAPI\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Session model.
 *
 * Сеанс.  Это сущность, характеризующая конкретное событие, время и место провередения. Например, для кино - это киносеанс.  id                  (*) - идентификатор сеанса venue_id            (*) - идентификатор площадки (Venue) event_id            (*) - идентификатор события (Event) hall_id             (*) - идентификатор зала (Hall) organizer_id            - идентификатор организатора (Organizer) session_time        (*) - время сеанса tags                    - список произвольных тегов sale_opening            - дата/время открытия продаж sale_closing            - дата/время закрытия продаж fee_percent             - процент сервисного сбора (по-умолчанию - 0) discount_percent        - процент скидки, предоставляемой партнером (по-умолчанию - 0) formats                 - список форматов фильма (для кино) sale_supported      (*) - разрешены ли продажи на данный сеанс prices                  - список цен can_pre_order           - разрешено ли создание пред-заказа available_seat_count    - число доступных для продажи мест additional              - служебное поле
 *
 * @package YagaSchedule\Server\Model
 * @author  Swagger Codegen team
 */
class Session
{
        /**
     * @var string|null
     * @SerializedName("id")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $id;

    /**
     * @var string|null
     * @SerializedName("venueId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $venueId;

    /**
     * @var string|null
     * @SerializedName("eventId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $eventId;

    /**
     * @var string|null
     * @SerializedName("hallId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $hallId;

    /**
     * @var string|null
     * @SerializedName("organizerId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $organizerId;

    /**
     * @var YagaSchedule\Server\Model\SessionTime|null
     * @SerializedName("sessionTime")
     * @Assert\Type("YagaSchedule\Server\Model\SessionTime")
     * @Type("YagaSchedule\Server\Model\SessionTime")
     */
    protected $sessionTime;

    /**
     * @var YagaSchedule\Server\Model\Tag[]|null
     * @SerializedName("tags")
     * @Assert\All({
     *   @Assert\Type("YagaSchedule\Server\Model\Tag")
     * })
     * @Type("array<YagaSchedule\Server\Model\Tag>")
     */
    protected $tags;

    /**
     * @var \DateTime|null
     * @SerializedName("saleOpening")
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected $saleOpening;

    /**
     * @var \DateTime|null
     * @SerializedName("saleClosing")
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected $saleClosing;

    /**
     * @var double|null
     * @SerializedName("feePercent")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected $feePercent;

    /**
     * @var double|null
     * @SerializedName("discountPercent")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected $discountPercent;

    /**
     * @var YagaSchedule\Server\Model\MovieFormat[]|null
     * @SerializedName("formats")
     * @Assert\All({
     *   @Assert\Type("YagaSchedule\Server\Model\MovieFormat")
     * })
     * @Type("array<YagaSchedule\Server\Model\MovieFormat>")
     */
    protected $formats;

    /**
     * @var bool|null
     * @SerializedName("saleSupported")
     * @Assert\Type("bool")
     * @Type("bool")
     */
    protected $saleSupported;

    /**
     * @var YagaSchedule\Server\Model\Money[]|null
     * @SerializedName("prices")
     * @Assert\All({
     *   @Assert\Type("YagaSchedule\Server\Model\Money")
     * })
     * @Type("array<YagaSchedule\Server\Model\Money>")
     */
    protected $prices;

    /**
     * @var YagaSchedule\Server\Model\PreOrderAllowance|null
     * @SerializedName("canPreOrder")
     * @Assert\Type("YagaSchedule\Server\Model\PreOrderAllowance")
     * @Type("YagaSchedule\Server\Model\PreOrderAllowance")
     */
    protected $canPreOrder;

    /**
     * @var int|null
     * @SerializedName("availableSeatCount")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $availableSeatCount;

    /**
     * @var array|null
     * @SerializedName("additional")
     * @Assert\Type("array")
     * @Type("array")
     */
    protected $additional;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->venueId = isset($data['venueId']) ? $data['venueId'] : null;
        $this->eventId = isset($data['eventId']) ? $data['eventId'] : null;
        $this->hallId = isset($data['hallId']) ? $data['hallId'] : null;
        $this->organizerId = isset($data['organizerId']) ? $data['organizerId'] : null;
        $this->sessionTime = isset($data['sessionTime']) ? $data['sessionTime'] : null;
        $this->tags = isset($data['tags']) ? $data['tags'] : null;
        $this->saleOpening = isset($data['saleOpening']) ? $data['saleOpening'] : null;
        $this->saleClosing = isset($data['saleClosing']) ? $data['saleClosing'] : null;
        $this->feePercent = isset($data['feePercent']) ? $data['feePercent'] : null;
        $this->discountPercent = isset($data['discountPercent']) ? $data['discountPercent'] : null;
        $this->formats = isset($data['formats']) ? $data['formats'] : null;
        $this->saleSupported = isset($data['saleSupported']) ? $data['saleSupported'] : null;
        $this->prices = isset($data['prices']) ? $data['prices'] : null;
        $this->canPreOrder = isset($data['canPreOrder']) ? $data['canPreOrder'] : null;
        $this->availableSeatCount = isset($data['availableSeatCount']) ? $data['availableSeatCount'] : null;
        $this->additional = isset($data['additional']) ? $data['additional'] : null;
    }

    /**
     * Gets id.
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param string|null $id
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets venueId.
     *
     * @return string|null
     */
    public function getVenueId()
    {
        return $this->venueId;
    }

    /**
     * Sets venueId.
     *
     * @param string|null $venueId
     *
     * @return $this
     */
    public function setVenueId($venueId = null)
    {
        $this->venueId = $venueId;

        return $this;
    }

    /**
     * Gets eventId.
     *
     * @return string|null
     */
    public function getEventId()
    {
        return $this->eventId;
    }

    /**
     * Sets eventId.
     *
     * @param string|null $eventId
     *
     * @return $this
     */
    public function setEventId($eventId = null)
    {
        $this->eventId = $eventId;

        return $this;
    }

    /**
     * Gets hallId.
     *
     * @return string|null
     */
    public function getHallId()
    {
        return $this->hallId;
    }

    /**
     * Sets hallId.
     *
     * @param string|null $hallId
     *
     * @return $this
     */
    public function setHallId($hallId = null)
    {
        $this->hallId = $hallId;

        return $this;
    }

    /**
     * Gets organizerId.
     *
     * @return string|null
     */
    public function getOrganizerId()
    {
        return $this->organizerId;
    }

    /**
     * Sets organizerId.
     *
     * @param string|null $organizerId
     *
     * @return $this
     */
    public function setOrganizerId($organizerId = null)
    {
        $this->organizerId = $organizerId;

        return $this;
    }

    /**
     * Gets sessionTime.
     *
     * @return \App\Services\YagaAPI\Model\SessionTime|null
     */
    public function getSessionTime()
    {
        return $this->sessionTime;
    }

    /**
     * Sets sessionTime.
     *
     * @param YagaSchedule\Server\Model\SessionTime|null $sessionTime
     *
     * @return $this
     */
    public function setSessionTime(SessionTime $sessionTime = null)
    {
        $this->sessionTime = $sessionTime;

        return $this;
    }

    /**
     * Gets tags.
     *
     * @return \App\Services\YagaAPI\Model\Tag[]|null
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Sets tags.
     *
     * @param YagaSchedule\Server\Model\Tag[]|null $tags
     *
     * @return $this
     */
    public function setTags(Tag $tags = null)
    {
        $this->tags = $tags;

        return $this;
    }

    /**
     * Gets saleOpening.
     *
     * @return \DateTime|null
     */
    public function getSaleOpening()
    {
        return $this->saleOpening;
    }

    /**
     * Sets saleOpening.
     *
     * @param \DateTime|null $saleOpening
     *
     * @return $this
     */
    public function setSaleOpening(\DateTime $saleOpening = null)
    {
        $this->saleOpening = $saleOpening;

        return $this;
    }

    /**
     * Gets saleClosing.
     *
     * @return \DateTime|null
     */
    public function getSaleClosing()
    {
        return $this->saleClosing;
    }

    /**
     * Sets saleClosing.
     *
     * @param \DateTime|null $saleClosing
     *
     * @return $this
     */
    public function setSaleClosing(\DateTime $saleClosing = null)
    {
        $this->saleClosing = $saleClosing;

        return $this;
    }

    /**
     * Gets feePercent.
     *
     * @return double|null
     */
    public function getFeePercent()
    {
        return $this->feePercent;
    }

    /**
     * Sets feePercent.
     *
     * @param double|null $feePercent
     *
     * @return $this
     */
    public function setFeePercent($feePercent = null)
    {
        $this->feePercent = $feePercent;

        return $this;
    }

    /**
     * Gets discountPercent.
     *
     * @return double|null
     */
    public function getDiscountPercent()
    {
        return $this->discountPercent;
    }

    /**
     * Sets discountPercent.
     *
     * @param double|null $discountPercent
     *
     * @return $this
     */
    public function setDiscountPercent($discountPercent = null)
    {
        $this->discountPercent = $discountPercent;

        return $this;
    }

    /**
     * Gets formats.
     *
     * @return \App\Services\YagaAPI\Model\MovieFormat[]|null
     */
    public function getFormats()
    {
        return $this->formats;
    }

    /**
     * Sets formats.
     *
     * @param YagaSchedule\Server\Model\MovieFormat[]|null $formats
     *
     * @return $this
     */
    public function setFormats(MovieFormat $formats = null)
    {
        $this->formats = $formats;

        return $this;
    }

    /**
     * Gets saleSupported.
     *
     * @return bool|null
     */
    public function isSaleSupported()
    {
        return $this->saleSupported;
    }

    /**
     * Sets saleSupported.
     *
     * @param bool|null $saleSupported
     *
     * @return $this
     */
    public function setSaleSupported($saleSupported = null)
    {
        $this->saleSupported = $saleSupported;

        return $this;
    }

    /**
     * Gets prices.
     *
     * @return \App\Services\YagaAPI\Model\Money[]|null
     */
    public function getPrices()
    {
        return $this->prices;
    }

    /**
     * Sets prices.
     *
     * @param YagaSchedule\Server\Model\Money[]|null $prices
     *
     * @return $this
     */
    public function setPrices(Money $prices = null)
    {
        $this->prices = $prices;

        return $this;
    }

    /**
     * Gets canPreOrder.
     *
     * @return \App\Services\YagaAPI\Model\PreOrderAllowance|null
     */
    public function getCanPreOrder()
    {
        return $this->canPreOrder;
    }

    /**
     * Sets canPreOrder.
     *
     * @param YagaSchedule\Server\Model\PreOrderAllowance|null $canPreOrder
     *
     * @return $this
     */
    public function setCanPreOrder(PreOrderAllowance $canPreOrder = null)
    {
        $this->canPreOrder = $canPreOrder;

        return $this;
    }

    /**
     * Gets availableSeatCount.
     *
     * @return int|null
     */
    public function getAvailableSeatCount()
    {
        return $this->availableSeatCount;
    }

    /**
     * Sets availableSeatCount.
     *
     * @param int|null $availableSeatCount
     *
     * @return $this
     */
    public function setAvailableSeatCount($availableSeatCount = null)
    {
        $this->availableSeatCount = $availableSeatCount;

        return $this;
    }

    /**
     * Gets additional.
     *
     * @return array|null
     */
    public function getAdditional()
    {
        return $this->additional;
    }

    /**
     * Sets additional.
     *
     * @param array|null $additional
     *
     * @return $this
     */
    public function setAdditional(array $additional = null)
    {
        $this->additional = $additional;

        return $this;
    }
}


